"""Generate tiny ECG-like synthetic paired data for public demos.

The generated signals are not participant data and are not scientifically
meaningful. They only exercise loading, preprocessing, windowing, model forward
passes, and metric code.

Usage:
    python scripts/make_synthetic_data.py --output data/synthetic/demo
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def _resolve_project_path(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else ROOT / p


def _gaussian(t: np.ndarray, center: float, width: float, amplitude: float) -> np.ndarray:
    return amplitude * np.exp(-0.5 * ((t - center) / width) ** 2)


def _synthetic_chest(t: np.ndarray, fs: int, heart_rate: float, rng: np.random.Generator) -> np.ndarray:
    duration = float(t[-1] + 1.0 / fs)
    period = 60.0 / heart_rate
    beats = np.arange(0.4, duration + period, period)
    signal = np.zeros_like(t, dtype=np.float32)

    for beat in beats:
        jitter = rng.normal(0.0, 0.012)
        c = beat + jitter
        signal += _gaussian(t, c - 0.18, 0.035, 0.10)      # P
        signal += _gaussian(t, c - 0.035, 0.012, -0.12)    # Q
        signal += _gaussian(t, c, 0.014, 1.00)             # R
        signal += _gaussian(t, c + 0.035, 0.018, -0.25)    # S
        signal += _gaussian(t, c + 0.26, 0.075, 0.30)      # T

    baseline = 0.04 * np.sin(2 * np.pi * 0.33 * t)
    noise = rng.normal(0.0, 0.015, size=t.shape)
    return (signal + baseline + noise).astype(np.float32)


def _synthetic_ear(chest: np.ndarray, t: np.ndarray, fs: int, rng: np.random.Generator) -> np.ndarray:
    delay = int(round(0.032 * fs))
    delayed = np.roll(chest, delay)
    delayed[:delay] = delayed[delay]
    motion = 0.06 * np.sin(2 * np.pi * 0.9 * t + rng.uniform(0.0, np.pi))
    contact_noise = rng.normal(0.0, 0.045, size=t.shape)
    return (0.55 * delayed + motion + contact_noise).astype(np.float32)


def generate_dataset(output: Path, subjects: int, duration_sec: float, fs: int, seed: int) -> None:
    output.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(seed)
    n_samples = int(duration_sec * fs)
    t = np.arange(n_samples, dtype=np.float32) / fs

    for idx in range(1, subjects + 1):
        subject_rng = np.random.default_rng(rng.integers(0, 2**32 - 1))
        heart_rate = 62.0 + 5.0 * idx + subject_rng.normal(0.0, 1.5)
        chest = _synthetic_chest(t, fs, heart_rate, subject_rng)
        ear = _synthetic_ear(chest, t, fs, subject_rng)
        paired = np.column_stack([ear, chest])
        np.savetxt(output / f"ecg_data_{idx:02d}.csv", paired, delimiter=",", fmt="%.8f")

    metadata = {
        "synthetic": True,
        "scientific_use": "demo only; not for performance claims",
        "schema": "headerless two-column CSV: column 0 ear ECG, column 1 chest-reference ECG",
        "subjects": subjects,
        "duration_sec": duration_sec,
        "fs": fs,
        "seed": seed,
    }
    (output / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    (output / "README.md").write_text(
        "# Synthetic Demo Data\n\n"
        "This folder contains ECG-like toy data generated by "
        "`scripts/make_synthetic_data.py`.\n\n"
        "It is not participant data, not clinically meaningful, and not suitable "
        "for scientific performance claims.\n",
        encoding="utf-8",
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", default="data/synthetic/demo")
    ap.add_argument("--subjects", type=int, default=3)
    ap.add_argument("--duration-sec", type=float, default=24.0)
    ap.add_argument("--fs", type=int, default=250)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    if args.subjects < 1:
        raise SystemExit("--subjects must be >= 1")
    if args.duration_sec < 12.0:
        raise SystemExit("--duration-sec must be >= 12 so preprocessing can trim and window data")

    output = _resolve_project_path(args.output)
    generate_dataset(output, args.subjects, args.duration_sec, args.fs, args.seed)
    print(f"Wrote synthetic demo data to {output}")
    print("Synthetic data is for pipeline demonstration only, not benchmark claims.")


if __name__ == "__main__":
    main()
